### ISSUE TITLE
Question about API Specification

### ISSUE THREAD

**Issue by manoger** [polterguy/magic#189]
Hello.

Is AISTA capable of exporting the generated CRUDs to an API spec like Open Api 3?
If no, is this functionality on the plans?

Thanks in advance.
Have a wonderful day!

**Comment by mshafiey** [comment]
Hello @manoger 
in fact you don't need any extra tools
you can make all CRUD api and for test it , you can invoke API in endpoint part , you can find it in  menu

**Comment by manoger** [comment]
Hello Mohsen.

Wouldn't be incredible at least to see speed up integration with some frontend framework or expose a CRUD API as a public API through some API Gateway like APIConnect through a swagger file? 😅

**Comment by mshafiey** [comment]
Yes sure, it can be really beautiful, but now we are busy to make some really incredible feature to make easy all steps needed to make CRUD application from scratch and publish it in our cloud (under 5 minutes 😎),but its an open source project 😃 start contribute in it ,if you interested 😊😊

**Comment by polterguy** [comment]
We'd love to have Open API spec support, it's not as simple as you think though. Magic only has *one* endpoint actually, so using Swagger or something is not possible. Creating an endpoint that builds the JSON required for Open API is possible, but a lot of work. This is something we're looking into delivering in the future, but not at the moment due to reasons Mohsen writes about. If you want to have a go at it, we'd love to approve a (high quality) pull request implementing it. My suggestion would be to implement it either as a separate plugin in C#, or use Hyperlambda to achieve it. If you create it as a separate plugin it could be an optional additional plugin.

**Comment by manoger** [comment]
Good to hear this! 
Thanks very much guys.
(:
